### ISSUE TITLE
KMS integration

### ISSUE THREAD

**Issue by DeviaVir** [pebble/flotilla#1]
KMS integration is breadcrumbed around:
https://github.com/thepwagner/flotilla/blob/master/src/flotilla/client/db.py#L46
https://github.com/thepwagner/flotilla/blob/master/src/flotilla/agent/db.py#L57
The latter is also where .service files are loaded back from the DB: could start with hash validation (or add signatures?), then continue on to KMS from there...

**Comment by thepwagner** [comment]
Encryption implemented. But it's a blackhole because I didn't get to decryption :P
