### ISSUE TITLE
Service without --health-check [interval] fails and rolls back template

### ISSUE THREAD

**Issue by DeviaVir** [pebble/flotilla#13]
<img width="1267" alt="screen shot 2016-01-11 at 12 07 45" src="https://cloud.githubusercontent.com/assets/777823/12232126/e1fcee40-b85c-11e5-833b-d4b12589bc4c.png">

When creating a new service, and we see that there's no health_check value, we should probably use a sane default.

**Comment by thepwagner** [comment]
I think this is caused by: https://github.com/thepwagner/flotilla/commit/c23448678e174cd99866c02da3dec4988a8e2c81

Interval=5 was shortest possible value when I got tired of waiting on ELB health checks; the conflict with `Timeout` might be the cause. Derp.

**Comment by DeviaVir** [comment]
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb-health-check.html confirms, will up the interval with 1 to have it be above the timeout..
