### ISSUE TITLE
Speed up deploys

### ISSUE THREAD

**Issue by DeviaVir** [pebble/flotilla#3]
Using messaging and/or DynamoDB stream to react to "unlock" events faster: deploys can go faster if they start one after the other.

**Comment by DeviaVir** [comment]
Using a queue (SQS) is probably a better idea than to marry to a certain DB (dynamo), let's close this for now.

**Comment by thepwagner** [comment]
I spent a while trying to make SNS work, but afaict you need a public IP to register as an HTTPS handler (and I dig keeping workers in private+NAT-ed subnets).

Latency of SQS+longpolling is tolerable (20-200ms when testing).
