### ISSUE TITLE
Referenced units

### ISSUE THREAD

**Issue by DeviaVir** [pebble/flotilla#5]
Units in a ServiceRevision that reference each other (i.e. proxy.service is After=worker.service) should map to deployed names.

**Comment by thepwagner** [comment]
https://github.com/thepwagner/flotilla/commit/07d197530c44e24d5552d8f44f312e66b7fe3461

I needed this yesterday: a revision containing fluentd-forwarder.service and journald-forwarder.service (where journald-forwarder uses fluentd so it shouldn't start until after).
